### ISSUE TITLE
New Post 

### ISSUE THREAD

**Issue by mrsid-31** [piharpi/jekyll-klise#27]
Do I need to create a new  directory for every new post?
And how can I enable the comment section?

**Comment by piharpi** [comment]
Yes, you need to create a new directory for every new post
To enable comment section you need to add `comment: true` at the front matter 

E.g
```mdx
---
title: Post title  
date: 2020-07-20 09:45:47 +07:00
description: Lorem ipsum dolor sit ammet
tags: [tag-a, tag-b]
comments: true # add here
--- 
```

**Comment by mrsid-31** [comment]
Thankyou so much.

**Comment by GymRat102** [comment]
I see this theme has jekyll compose plugin so I guess the theme suggests to use it to streamline the new post creation right?

But by default jekyll compose create a new .md file directly inside _post/ folder, instead of in a subdirectory containing the new post.

An issue from jekyll-compose plugin describe the same issue but it doesn't provide any solution.
- https://github.com/jekyll/jekyll-compose/issues/122

I could definitely write a shell script to automate it, but just curious how you guys solve this problem
